#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="abc")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_invoice_detail(tbl_invoice_detail instance);
    partial void Updatetbl_invoice_detail(tbl_invoice_detail instance);
    partial void Deletetbl_invoice_detail(tbl_invoice_detail instance);
    partial void Inserttbl_user_master(tbl_user_master instance);
    partial void Updatetbl_user_master(tbl_user_master instance);
    partial void Deletetbl_user_master(tbl_user_master instance);
    partial void Inserttbl_invoice_master(tbl_invoice_master instance);
    partial void Updatetbl_invoice_master(tbl_invoice_master instance);
    partial void Deletetbl_invoice_master(tbl_invoice_master instance);
    partial void Inserttbl_item_master(tbl_item_master instance);
    partial void Updatetbl_item_master(tbl_item_master instance);
    partial void Deletetbl_item_master(tbl_item_master instance);
    partial void Inserttbl_role_master(tbl_role_master instance);
    partial void Updatetbl_role_master(tbl_role_master instance);
    partial void Deletetbl_role_master(tbl_role_master instance);
    partial void Inserttbl_uom_master(tbl_uom_master instance);
    partial void Updatetbl_uom_master(tbl_uom_master instance);
    partial void Deletetbl_uom_master(tbl_uom_master instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::DAL.Properties.Settings.Default.abcConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_invoice_detail> tbl_invoice_details
		{
			get
			{
				return this.GetTable<tbl_invoice_detail>();
			}
		}
		
		public System.Data.Linq.Table<tbl_user_master> tbl_user_masters
		{
			get
			{
				return this.GetTable<tbl_user_master>();
			}
		}
		
		public System.Data.Linq.Table<tbl_invoice_master> tbl_invoice_masters
		{
			get
			{
				return this.GetTable<tbl_invoice_master>();
			}
		}
		
		public System.Data.Linq.Table<tbl_item_master> tbl_item_masters
		{
			get
			{
				return this.GetTable<tbl_item_master>();
			}
		}
		
		public System.Data.Linq.Table<tbl_role_master> tbl_role_masters
		{
			get
			{
				return this.GetTable<tbl_role_master>();
			}
		}
		
		public System.Data.Linq.Table<tbl_uom_master> tbl_uom_masters
		{
			get
			{
				return this.GetTable<tbl_uom_master>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_invoice_details")]
	public partial class tbl_invoice_detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _inv_detail_no;
		
		private int _inv_no;
		
		private int _item_id;
		
		private System.Nullable<double> _item_cost_price;
		
		private System.Nullable<double> _item_price;
		
		private System.Nullable<double> _item_qty;
		
		private System.Nullable<double> _sub_total;
		
		private System.Nullable<int> _uom_id;
		
		private EntityRef<tbl_invoice_master> _tbl_invoice_master;
		
		private EntityRef<tbl_item_master> _tbl_item_master;
		
		private EntityRef<tbl_uom_master> _tbl_uom_master;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oninv_detail_noChanging(int value);
    partial void Oninv_detail_noChanged();
    partial void Oninv_noChanging(int value);
    partial void Oninv_noChanged();
    partial void Onitem_idChanging(int value);
    partial void Onitem_idChanged();
    partial void Onitem_cost_priceChanging(System.Nullable<double> value);
    partial void Onitem_cost_priceChanged();
    partial void Onitem_priceChanging(System.Nullable<double> value);
    partial void Onitem_priceChanged();
    partial void Onitem_qtyChanging(System.Nullable<double> value);
    partial void Onitem_qtyChanged();
    partial void Onsub_totalChanging(System.Nullable<double> value);
    partial void Onsub_totalChanged();
    partial void Onuom_idChanging(System.Nullable<int> value);
    partial void Onuom_idChanged();
    #endregion
		
		public tbl_invoice_detail()
		{
			this._tbl_invoice_master = default(EntityRef<tbl_invoice_master>);
			this._tbl_item_master = default(EntityRef<tbl_item_master>);
			this._tbl_uom_master = default(EntityRef<tbl_uom_master>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inv_detail_no", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int inv_detail_no
		{
			get
			{
				return this._inv_detail_no;
			}
			set
			{
				if ((this._inv_detail_no != value))
				{
					this.Oninv_detail_noChanging(value);
					this.SendPropertyChanging();
					this._inv_detail_no = value;
					this.SendPropertyChanged("inv_detail_no");
					this.Oninv_detail_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inv_no", DbType="Int NOT NULL")]
		public int inv_no
		{
			get
			{
				return this._inv_no;
			}
			set
			{
				if ((this._inv_no != value))
				{
					if (this._tbl_invoice_master.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oninv_noChanging(value);
					this.SendPropertyChanging();
					this._inv_no = value;
					this.SendPropertyChanged("inv_no");
					this.Oninv_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_id", DbType="Int NOT NULL")]
		public int item_id
		{
			get
			{
				return this._item_id;
			}
			set
			{
				if ((this._item_id != value))
				{
					if (this._tbl_item_master.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onitem_idChanging(value);
					this.SendPropertyChanging();
					this._item_id = value;
					this.SendPropertyChanged("item_id");
					this.Onitem_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_cost_price", DbType="Float")]
		public System.Nullable<double> item_cost_price
		{
			get
			{
				return this._item_cost_price;
			}
			set
			{
				if ((this._item_cost_price != value))
				{
					this.Onitem_cost_priceChanging(value);
					this.SendPropertyChanging();
					this._item_cost_price = value;
					this.SendPropertyChanged("item_cost_price");
					this.Onitem_cost_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_price", DbType="Float")]
		public System.Nullable<double> item_price
		{
			get
			{
				return this._item_price;
			}
			set
			{
				if ((this._item_price != value))
				{
					this.Onitem_priceChanging(value);
					this.SendPropertyChanging();
					this._item_price = value;
					this.SendPropertyChanged("item_price");
					this.Onitem_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_qty", DbType="Float")]
		public System.Nullable<double> item_qty
		{
			get
			{
				return this._item_qty;
			}
			set
			{
				if ((this._item_qty != value))
				{
					this.Onitem_qtyChanging(value);
					this.SendPropertyChanging();
					this._item_qty = value;
					this.SendPropertyChanged("item_qty");
					this.Onitem_qtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sub_total", DbType="Float")]
		public System.Nullable<double> sub_total
		{
			get
			{
				return this._sub_total;
			}
			set
			{
				if ((this._sub_total != value))
				{
					this.Onsub_totalChanging(value);
					this.SendPropertyChanging();
					this._sub_total = value;
					this.SendPropertyChanged("sub_total");
					this.Onsub_totalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uom_id", DbType="Int")]
		public System.Nullable<int> uom_id
		{
			get
			{
				return this._uom_id;
			}
			set
			{
				if ((this._uom_id != value))
				{
					if (this._tbl_uom_master.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuom_idChanging(value);
					this.SendPropertyChanging();
					this._uom_id = value;
					this.SendPropertyChanged("uom_id");
					this.Onuom_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_invoice_master_tbl_invoice_detail", Storage="_tbl_invoice_master", ThisKey="inv_no", OtherKey="inv_no", IsForeignKey=true)]
		public tbl_invoice_master tbl_invoice_master
		{
			get
			{
				return this._tbl_invoice_master.Entity;
			}
			set
			{
				tbl_invoice_master previousValue = this._tbl_invoice_master.Entity;
				if (((previousValue != value) 
							|| (this._tbl_invoice_master.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_invoice_master.Entity = null;
						previousValue.tbl_invoice_details.Remove(this);
					}
					this._tbl_invoice_master.Entity = value;
					if ((value != null))
					{
						value.tbl_invoice_details.Add(this);
						this._inv_no = value.inv_no;
					}
					else
					{
						this._inv_no = default(int);
					}
					this.SendPropertyChanged("tbl_invoice_master");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_item_master_tbl_invoice_detail", Storage="_tbl_item_master", ThisKey="item_id", OtherKey="item_id", IsForeignKey=true)]
		public tbl_item_master tbl_item_master
		{
			get
			{
				return this._tbl_item_master.Entity;
			}
			set
			{
				tbl_item_master previousValue = this._tbl_item_master.Entity;
				if (((previousValue != value) 
							|| (this._tbl_item_master.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_item_master.Entity = null;
						previousValue.tbl_invoice_details.Remove(this);
					}
					this._tbl_item_master.Entity = value;
					if ((value != null))
					{
						value.tbl_invoice_details.Add(this);
						this._item_id = value.item_id;
					}
					else
					{
						this._item_id = default(int);
					}
					this.SendPropertyChanged("tbl_item_master");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_uom_master_tbl_invoice_detail", Storage="_tbl_uom_master", ThisKey="uom_id", OtherKey="uom_id", IsForeignKey=true)]
		public tbl_uom_master tbl_uom_master
		{
			get
			{
				return this._tbl_uom_master.Entity;
			}
			set
			{
				tbl_uom_master previousValue = this._tbl_uom_master.Entity;
				if (((previousValue != value) 
							|| (this._tbl_uom_master.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_uom_master.Entity = null;
						previousValue.tbl_invoice_details.Remove(this);
					}
					this._tbl_uom_master.Entity = value;
					if ((value != null))
					{
						value.tbl_invoice_details.Add(this);
						this._uom_id = value.uom_id;
					}
					else
					{
						this._uom_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_uom_master");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_user_master")]
	public partial class tbl_user_master : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_id;
		
		private string _user_name;
		
		private string _password;
		
		private int _role_id;
		
		private string _f_name;
		
		private string _l_name;
		
		private string _address;
		
		private System.Nullable<bool> _is_active;
		
		private EntitySet<tbl_invoice_master> _tbl_invoice_masters;
		
		private EntityRef<tbl_role_master> _tbl_role_master;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Onrole_idChanging(int value);
    partial void Onrole_idChanged();
    partial void Onf_nameChanging(string value);
    partial void Onf_nameChanged();
    partial void Onl_nameChanging(string value);
    partial void Onl_nameChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void Onis_activeChanging(System.Nullable<bool> value);
    partial void Onis_activeChanged();
    #endregion
		
		public tbl_user_master()
		{
			this._tbl_invoice_masters = new EntitySet<tbl_invoice_master>(new Action<tbl_invoice_master>(this.attach_tbl_invoice_masters), new Action<tbl_invoice_master>(this.detach_tbl_invoice_masters));
			this._tbl_role_master = default(EntityRef<tbl_role_master>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="VarChar(250)")]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(250)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role_id", DbType="Int NOT NULL")]
		public int role_id
		{
			get
			{
				return this._role_id;
			}
			set
			{
				if ((this._role_id != value))
				{
					if (this._tbl_role_master.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onrole_idChanging(value);
					this.SendPropertyChanging();
					this._role_id = value;
					this.SendPropertyChanged("role_id");
					this.Onrole_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_name", DbType="VarChar(250)")]
		public string f_name
		{
			get
			{
				return this._f_name;
			}
			set
			{
				if ((this._f_name != value))
				{
					this.Onf_nameChanging(value);
					this.SendPropertyChanging();
					this._f_name = value;
					this.SendPropertyChanged("f_name");
					this.Onf_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l_name", DbType="VarChar(250)")]
		public string l_name
		{
			get
			{
				return this._l_name;
			}
			set
			{
				if ((this._l_name != value))
				{
					this.Onl_nameChanging(value);
					this.SendPropertyChanging();
					this._l_name = value;
					this.SendPropertyChanged("l_name");
					this.Onl_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(250)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_active", DbType="Bit")]
		public System.Nullable<bool> is_active
		{
			get
			{
				return this._is_active;
			}
			set
			{
				if ((this._is_active != value))
				{
					this.Onis_activeChanging(value);
					this.SendPropertyChanging();
					this._is_active = value;
					this.SendPropertyChanged("is_active");
					this.Onis_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_user_master_tbl_invoice_master", Storage="_tbl_invoice_masters", ThisKey="user_id", OtherKey="customer_id")]
		public EntitySet<tbl_invoice_master> tbl_invoice_masters
		{
			get
			{
				return this._tbl_invoice_masters;
			}
			set
			{
				this._tbl_invoice_masters.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_role_master_tbl_user_master", Storage="_tbl_role_master", ThisKey="role_id", OtherKey="role_id", IsForeignKey=true)]
		public tbl_role_master tbl_role_master
		{
			get
			{
				return this._tbl_role_master.Entity;
			}
			set
			{
				tbl_role_master previousValue = this._tbl_role_master.Entity;
				if (((previousValue != value) 
							|| (this._tbl_role_master.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_role_master.Entity = null;
						previousValue.tbl_user_masters.Remove(this);
					}
					this._tbl_role_master.Entity = value;
					if ((value != null))
					{
						value.tbl_user_masters.Add(this);
						this._role_id = value.role_id;
					}
					else
					{
						this._role_id = default(int);
					}
					this.SendPropertyChanged("tbl_role_master");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_invoice_masters(tbl_invoice_master entity)
		{
			this.SendPropertyChanging();
			entity.tbl_user_master = this;
		}
		
		private void detach_tbl_invoice_masters(tbl_invoice_master entity)
		{
			this.SendPropertyChanging();
			entity.tbl_user_master = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_invoice_master")]
	public partial class tbl_invoice_master : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _inv_no;
		
		private int _customer_id;
		
		private System.Nullable<System.DateTime> _inv_date;
		
		private System.Nullable<double> _total_price;
		
		private System.Nullable<double> _total_qty;
		
		private System.Nullable<int> _inv_stat;
		
		private System.Nullable<bool> _is_deleted;
		
		private string _deleted_user_id;
		
		private string _deleted_date;
		
		private EntitySet<tbl_invoice_detail> _tbl_invoice_details;
		
		private EntityRef<tbl_user_master> _tbl_user_master;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oninv_noChanging(int value);
    partial void Oninv_noChanged();
    partial void Oncustomer_idChanging(int value);
    partial void Oncustomer_idChanged();
    partial void Oninv_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oninv_dateChanged();
    partial void Ontotal_priceChanging(System.Nullable<double> value);
    partial void Ontotal_priceChanged();
    partial void Ontotal_qtyChanging(System.Nullable<double> value);
    partial void Ontotal_qtyChanged();
    partial void Oninv_statChanging(System.Nullable<int> value);
    partial void Oninv_statChanged();
    partial void Onis_deletedChanging(System.Nullable<bool> value);
    partial void Onis_deletedChanged();
    partial void Ondeleted_user_idChanging(string value);
    partial void Ondeleted_user_idChanged();
    partial void Ondeleted_dateChanging(string value);
    partial void Ondeleted_dateChanged();
    #endregion
		
		public tbl_invoice_master()
		{
			this._tbl_invoice_details = new EntitySet<tbl_invoice_detail>(new Action<tbl_invoice_detail>(this.attach_tbl_invoice_details), new Action<tbl_invoice_detail>(this.detach_tbl_invoice_details));
			this._tbl_user_master = default(EntityRef<tbl_user_master>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inv_no", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int inv_no
		{
			get
			{
				return this._inv_no;
			}
			set
			{
				if ((this._inv_no != value))
				{
					this.Oninv_noChanging(value);
					this.SendPropertyChanging();
					this._inv_no = value;
					this.SendPropertyChanged("inv_no");
					this.Oninv_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_id", DbType="Int NOT NULL")]
		public int customer_id
		{
			get
			{
				return this._customer_id;
			}
			set
			{
				if ((this._customer_id != value))
				{
					if (this._tbl_user_master.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncustomer_idChanging(value);
					this.SendPropertyChanging();
					this._customer_id = value;
					this.SendPropertyChanged("customer_id");
					this.Oncustomer_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inv_date", DbType="Date")]
		public System.Nullable<System.DateTime> inv_date
		{
			get
			{
				return this._inv_date;
			}
			set
			{
				if ((this._inv_date != value))
				{
					this.Oninv_dateChanging(value);
					this.SendPropertyChanging();
					this._inv_date = value;
					this.SendPropertyChanged("inv_date");
					this.Oninv_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_price", DbType="Float")]
		public System.Nullable<double> total_price
		{
			get
			{
				return this._total_price;
			}
			set
			{
				if ((this._total_price != value))
				{
					this.Ontotal_priceChanging(value);
					this.SendPropertyChanging();
					this._total_price = value;
					this.SendPropertyChanged("total_price");
					this.Ontotal_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_qty", DbType="Float")]
		public System.Nullable<double> total_qty
		{
			get
			{
				return this._total_qty;
			}
			set
			{
				if ((this._total_qty != value))
				{
					this.Ontotal_qtyChanging(value);
					this.SendPropertyChanging();
					this._total_qty = value;
					this.SendPropertyChanged("total_qty");
					this.Ontotal_qtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inv_stat", DbType="Int")]
		public System.Nullable<int> inv_stat
		{
			get
			{
				return this._inv_stat;
			}
			set
			{
				if ((this._inv_stat != value))
				{
					this.Oninv_statChanging(value);
					this.SendPropertyChanging();
					this._inv_stat = value;
					this.SendPropertyChanged("inv_stat");
					this.Oninv_statChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_deleted", DbType="Bit")]
		public System.Nullable<bool> is_deleted
		{
			get
			{
				return this._is_deleted;
			}
			set
			{
				if ((this._is_deleted != value))
				{
					this.Onis_deletedChanging(value);
					this.SendPropertyChanging();
					this._is_deleted = value;
					this.SendPropertyChanged("is_deleted");
					this.Onis_deletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted_user_id", DbType="NChar(10)")]
		public string deleted_user_id
		{
			get
			{
				return this._deleted_user_id;
			}
			set
			{
				if ((this._deleted_user_id != value))
				{
					this.Ondeleted_user_idChanging(value);
					this.SendPropertyChanging();
					this._deleted_user_id = value;
					this.SendPropertyChanged("deleted_user_id");
					this.Ondeleted_user_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted_date", DbType="NChar(10)")]
		public string deleted_date
		{
			get
			{
				return this._deleted_date;
			}
			set
			{
				if ((this._deleted_date != value))
				{
					this.Ondeleted_dateChanging(value);
					this.SendPropertyChanging();
					this._deleted_date = value;
					this.SendPropertyChanged("deleted_date");
					this.Ondeleted_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_invoice_master_tbl_invoice_detail", Storage="_tbl_invoice_details", ThisKey="inv_no", OtherKey="inv_no")]
		public EntitySet<tbl_invoice_detail> tbl_invoice_details
		{
			get
			{
				return this._tbl_invoice_details;
			}
			set
			{
				this._tbl_invoice_details.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_user_master_tbl_invoice_master", Storage="_tbl_user_master", ThisKey="customer_id", OtherKey="user_id", IsForeignKey=true)]
		public tbl_user_master tbl_user_master
		{
			get
			{
				return this._tbl_user_master.Entity;
			}
			set
			{
				tbl_user_master previousValue = this._tbl_user_master.Entity;
				if (((previousValue != value) 
							|| (this._tbl_user_master.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_user_master.Entity = null;
						previousValue.tbl_invoice_masters.Remove(this);
					}
					this._tbl_user_master.Entity = value;
					if ((value != null))
					{
						value.tbl_invoice_masters.Add(this);
						this._customer_id = value.user_id;
					}
					else
					{
						this._customer_id = default(int);
					}
					this.SendPropertyChanged("tbl_user_master");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_invoice_details(tbl_invoice_detail entity)
		{
			this.SendPropertyChanging();
			entity.tbl_invoice_master = this;
		}
		
		private void detach_tbl_invoice_details(tbl_invoice_detail entity)
		{
			this.SendPropertyChanging();
			entity.tbl_invoice_master = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_item_master")]
	public partial class tbl_item_master : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _item_id;
		
		private string _item_code;
		
		private string _item_desc;
		
		private int _uom_id;
		
		private System.Nullable<double> _item_price;
		
		private System.Nullable<double> _item_cost_price;
		
		private System.Nullable<bool> _is_vehicle;
		
		private string _vehicle_type_desc;
		
		private string _vehicle_model_desc;
		
		private System.Nullable<bool> _is_active;
		
		private EntitySet<tbl_invoice_detail> _tbl_invoice_details;
		
		private EntityRef<tbl_uom_master> _tbl_uom_master;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onitem_idChanging(int value);
    partial void Onitem_idChanged();
    partial void Onitem_codeChanging(string value);
    partial void Onitem_codeChanged();
    partial void Onitem_descChanging(string value);
    partial void Onitem_descChanged();
    partial void Onuom_idChanging(int value);
    partial void Onuom_idChanged();
    partial void Onitem_priceChanging(System.Nullable<double> value);
    partial void Onitem_priceChanged();
    partial void Onitem_cost_priceChanging(System.Nullable<double> value);
    partial void Onitem_cost_priceChanged();
    partial void Onis_vehicleChanging(System.Nullable<bool> value);
    partial void Onis_vehicleChanged();
    partial void Onvehicle_type_descChanging(string value);
    partial void Onvehicle_type_descChanged();
    partial void Onvehicle_model_descChanging(string value);
    partial void Onvehicle_model_descChanged();
    partial void Onis_activeChanging(System.Nullable<bool> value);
    partial void Onis_activeChanged();
    #endregion
		
		public tbl_item_master()
		{
			this._tbl_invoice_details = new EntitySet<tbl_invoice_detail>(new Action<tbl_invoice_detail>(this.attach_tbl_invoice_details), new Action<tbl_invoice_detail>(this.detach_tbl_invoice_details));
			this._tbl_uom_master = default(EntityRef<tbl_uom_master>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int item_id
		{
			get
			{
				return this._item_id;
			}
			set
			{
				if ((this._item_id != value))
				{
					this.Onitem_idChanging(value);
					this.SendPropertyChanging();
					this._item_id = value;
					this.SendPropertyChanged("item_id");
					this.Onitem_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_code", DbType="VarChar(250)")]
		public string item_code
		{
			get
			{
				return this._item_code;
			}
			set
			{
				if ((this._item_code != value))
				{
					this.Onitem_codeChanging(value);
					this.SendPropertyChanging();
					this._item_code = value;
					this.SendPropertyChanged("item_code");
					this.Onitem_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_desc", DbType="VarChar(250)")]
		public string item_desc
		{
			get
			{
				return this._item_desc;
			}
			set
			{
				if ((this._item_desc != value))
				{
					this.Onitem_descChanging(value);
					this.SendPropertyChanging();
					this._item_desc = value;
					this.SendPropertyChanged("item_desc");
					this.Onitem_descChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uom_id", DbType="Int NOT NULL")]
		public int uom_id
		{
			get
			{
				return this._uom_id;
			}
			set
			{
				if ((this._uom_id != value))
				{
					if (this._tbl_uom_master.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuom_idChanging(value);
					this.SendPropertyChanging();
					this._uom_id = value;
					this.SendPropertyChanged("uom_id");
					this.Onuom_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_price", DbType="Float")]
		public System.Nullable<double> item_price
		{
			get
			{
				return this._item_price;
			}
			set
			{
				if ((this._item_price != value))
				{
					this.Onitem_priceChanging(value);
					this.SendPropertyChanging();
					this._item_price = value;
					this.SendPropertyChanged("item_price");
					this.Onitem_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_cost_price", DbType="Float")]
		public System.Nullable<double> item_cost_price
		{
			get
			{
				return this._item_cost_price;
			}
			set
			{
				if ((this._item_cost_price != value))
				{
					this.Onitem_cost_priceChanging(value);
					this.SendPropertyChanging();
					this._item_cost_price = value;
					this.SendPropertyChanged("item_cost_price");
					this.Onitem_cost_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_vehicle", DbType="Bit")]
		public System.Nullable<bool> is_vehicle
		{
			get
			{
				return this._is_vehicle;
			}
			set
			{
				if ((this._is_vehicle != value))
				{
					this.Onis_vehicleChanging(value);
					this.SendPropertyChanging();
					this._is_vehicle = value;
					this.SendPropertyChanged("is_vehicle");
					this.Onis_vehicleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vehicle_type_desc", DbType="VarChar(250)")]
		public string vehicle_type_desc
		{
			get
			{
				return this._vehicle_type_desc;
			}
			set
			{
				if ((this._vehicle_type_desc != value))
				{
					this.Onvehicle_type_descChanging(value);
					this.SendPropertyChanging();
					this._vehicle_type_desc = value;
					this.SendPropertyChanged("vehicle_type_desc");
					this.Onvehicle_type_descChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vehicle_model_desc", DbType="VarChar(250)")]
		public string vehicle_model_desc
		{
			get
			{
				return this._vehicle_model_desc;
			}
			set
			{
				if ((this._vehicle_model_desc != value))
				{
					this.Onvehicle_model_descChanging(value);
					this.SendPropertyChanging();
					this._vehicle_model_desc = value;
					this.SendPropertyChanged("vehicle_model_desc");
					this.Onvehicle_model_descChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_active", DbType="Bit")]
		public System.Nullable<bool> is_active
		{
			get
			{
				return this._is_active;
			}
			set
			{
				if ((this._is_active != value))
				{
					this.Onis_activeChanging(value);
					this.SendPropertyChanging();
					this._is_active = value;
					this.SendPropertyChanged("is_active");
					this.Onis_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_item_master_tbl_invoice_detail", Storage="_tbl_invoice_details", ThisKey="item_id", OtherKey="item_id")]
		public EntitySet<tbl_invoice_detail> tbl_invoice_details
		{
			get
			{
				return this._tbl_invoice_details;
			}
			set
			{
				this._tbl_invoice_details.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_uom_master_tbl_item_master", Storage="_tbl_uom_master", ThisKey="uom_id", OtherKey="uom_id", IsForeignKey=true)]
		public tbl_uom_master tbl_uom_master
		{
			get
			{
				return this._tbl_uom_master.Entity;
			}
			set
			{
				tbl_uom_master previousValue = this._tbl_uom_master.Entity;
				if (((previousValue != value) 
							|| (this._tbl_uom_master.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_uom_master.Entity = null;
						previousValue.tbl_item_masters.Remove(this);
					}
					this._tbl_uom_master.Entity = value;
					if ((value != null))
					{
						value.tbl_item_masters.Add(this);
						this._uom_id = value.uom_id;
					}
					else
					{
						this._uom_id = default(int);
					}
					this.SendPropertyChanged("tbl_uom_master");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_invoice_details(tbl_invoice_detail entity)
		{
			this.SendPropertyChanging();
			entity.tbl_item_master = this;
		}
		
		private void detach_tbl_invoice_details(tbl_invoice_detail entity)
		{
			this.SendPropertyChanging();
			entity.tbl_item_master = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_role_master")]
	public partial class tbl_role_master : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _role_id;
		
		private string _role_desc;
		
		private System.Nullable<bool> _is_active;
		
		private EntitySet<tbl_user_master> _tbl_user_masters;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onrole_idChanging(int value);
    partial void Onrole_idChanged();
    partial void Onrole_descChanging(string value);
    partial void Onrole_descChanged();
    partial void Onis_activeChanging(System.Nullable<bool> value);
    partial void Onis_activeChanged();
    #endregion
		
		public tbl_role_master()
		{
			this._tbl_user_masters = new EntitySet<tbl_user_master>(new Action<tbl_user_master>(this.attach_tbl_user_masters), new Action<tbl_user_master>(this.detach_tbl_user_masters));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int role_id
		{
			get
			{
				return this._role_id;
			}
			set
			{
				if ((this._role_id != value))
				{
					this.Onrole_idChanging(value);
					this.SendPropertyChanging();
					this._role_id = value;
					this.SendPropertyChanged("role_id");
					this.Onrole_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role_desc", DbType="VarChar(250)")]
		public string role_desc
		{
			get
			{
				return this._role_desc;
			}
			set
			{
				if ((this._role_desc != value))
				{
					this.Onrole_descChanging(value);
					this.SendPropertyChanging();
					this._role_desc = value;
					this.SendPropertyChanged("role_desc");
					this.Onrole_descChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_active", DbType="Bit")]
		public System.Nullable<bool> is_active
		{
			get
			{
				return this._is_active;
			}
			set
			{
				if ((this._is_active != value))
				{
					this.Onis_activeChanging(value);
					this.SendPropertyChanging();
					this._is_active = value;
					this.SendPropertyChanged("is_active");
					this.Onis_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_role_master_tbl_user_master", Storage="_tbl_user_masters", ThisKey="role_id", OtherKey="role_id")]
		public EntitySet<tbl_user_master> tbl_user_masters
		{
			get
			{
				return this._tbl_user_masters;
			}
			set
			{
				this._tbl_user_masters.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_user_masters(tbl_user_master entity)
		{
			this.SendPropertyChanging();
			entity.tbl_role_master = this;
		}
		
		private void detach_tbl_user_masters(tbl_user_master entity)
		{
			this.SendPropertyChanging();
			entity.tbl_role_master = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_uom_master")]
	public partial class tbl_uom_master : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _uom_id;
		
		private string _uom_desc;
		
		private System.Nullable<bool> _is_active;
		
		private EntitySet<tbl_invoice_detail> _tbl_invoice_details;
		
		private EntitySet<tbl_item_master> _tbl_item_masters;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuom_idChanging(int value);
    partial void Onuom_idChanged();
    partial void Onuom_descChanging(string value);
    partial void Onuom_descChanged();
    partial void Onis_activeChanging(System.Nullable<bool> value);
    partial void Onis_activeChanged();
    #endregion
		
		public tbl_uom_master()
		{
			this._tbl_invoice_details = new EntitySet<tbl_invoice_detail>(new Action<tbl_invoice_detail>(this.attach_tbl_invoice_details), new Action<tbl_invoice_detail>(this.detach_tbl_invoice_details));
			this._tbl_item_masters = new EntitySet<tbl_item_master>(new Action<tbl_item_master>(this.attach_tbl_item_masters), new Action<tbl_item_master>(this.detach_tbl_item_masters));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uom_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int uom_id
		{
			get
			{
				return this._uom_id;
			}
			set
			{
				if ((this._uom_id != value))
				{
					this.Onuom_idChanging(value);
					this.SendPropertyChanging();
					this._uom_id = value;
					this.SendPropertyChanged("uom_id");
					this.Onuom_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uom_desc", DbType="VarChar(250)")]
		public string uom_desc
		{
			get
			{
				return this._uom_desc;
			}
			set
			{
				if ((this._uom_desc != value))
				{
					this.Onuom_descChanging(value);
					this.SendPropertyChanging();
					this._uom_desc = value;
					this.SendPropertyChanged("uom_desc");
					this.Onuom_descChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_active", DbType="Bit")]
		public System.Nullable<bool> is_active
		{
			get
			{
				return this._is_active;
			}
			set
			{
				if ((this._is_active != value))
				{
					this.Onis_activeChanging(value);
					this.SendPropertyChanging();
					this._is_active = value;
					this.SendPropertyChanged("is_active");
					this.Onis_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_uom_master_tbl_invoice_detail", Storage="_tbl_invoice_details", ThisKey="uom_id", OtherKey="uom_id")]
		public EntitySet<tbl_invoice_detail> tbl_invoice_details
		{
			get
			{
				return this._tbl_invoice_details;
			}
			set
			{
				this._tbl_invoice_details.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_uom_master_tbl_item_master", Storage="_tbl_item_masters", ThisKey="uom_id", OtherKey="uom_id")]
		public EntitySet<tbl_item_master> tbl_item_masters
		{
			get
			{
				return this._tbl_item_masters;
			}
			set
			{
				this._tbl_item_masters.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_invoice_details(tbl_invoice_detail entity)
		{
			this.SendPropertyChanging();
			entity.tbl_uom_master = this;
		}
		
		private void detach_tbl_invoice_details(tbl_invoice_detail entity)
		{
			this.SendPropertyChanging();
			entity.tbl_uom_master = null;
		}
		
		private void attach_tbl_item_masters(tbl_item_master entity)
		{
			this.SendPropertyChanging();
			entity.tbl_uom_master = this;
		}
		
		private void detach_tbl_item_masters(tbl_item_master entity)
		{
			this.SendPropertyChanging();
			entity.tbl_uom_master = null;
		}
	}
}
#pragma warning restore 1591
